let CompaniesData = [
  {
    id: 1,
    Titel: "CompaniesData",
    serLink: "https://in.indeed.com/",
    serviceImg: "Pegipegi.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 2,
    Titel: "Kompas Group",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Kompas-Group.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 3,
    Titel: "Group Avows",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Group-Avows.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 4,
    Titel: "Lalamove",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Lalamove.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 5,
    Titel: "PT Midas Daya Teknologi",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Lalamove.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 6,
    Titel: "Siemens",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Lalamove.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 7,
    Titel: "eFishery",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Lalamove.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 8,
    Titel: "Cermati",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Lalamove.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 9,
    Titel: "Whiz (YC W22)",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Whiz.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 10,
    Titel: "JULO",
    serLink: "https://in.indeed.com/",
    serviceImg: "/JULO.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 11,
    Titel: "UOB",
    serLink: "https://in.indeed.com/",
    serviceImg: "/JULO.png",
    Review: "4.9 | 50+ reviews",
  },
  {
    id: 12,
    Titel: "Logisly",
    serLink: "https://in.indeed.com/",
    serviceImg: "/JULO.png",
    Review: "4.9 | 50+ reviews",
  },
];

export default CompaniesData;
