let FeaturedData = [
  {
    id: 1,
    Titel: "Tech Rookie Internship Program (TRIP) - iOS Eng...",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-1.png",
    review: "4.1 | 50+ reviews",
    h1: "PT Midas Daya Teknologi",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 2,
    Titel: "Business Development Support - Bandung",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-2.png",
    review: "4.1 | 50+ reviews",
    h1: "Lalamove",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 3,
    Titel: "Program Management Officer - Multimedia Nusantara Poly...",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-3.png",
    review: "4.1 | 50+ reviews",
    h1: "Kompas Group",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 4,
    Titel: "Cyber Security Engineer",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-4.png",
    review: "4.1 | 50+ reviews",
    h1: "Cyber Security Engineer",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 5,
    Titel: "Visual Designer (Freelance)",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-5.png",
    review: "4.1 | 50+ reviews",
    h1: "Whiz (YC W22)",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 6,
    Titel: "Risk Manager",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-6.png",
    review: "4.1 | 50+ reviews",
    h1: "Julo",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 7,
    Titel: "Transporter Management ExecutiveTransporter Management Executive",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-7.png",
    review: "4.1 | 50+ reviews",
    h1: "Logisly",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
  {
    id: 8,
    Titel: "Capacity & Configuration",
    serLink: "https://in.indeed.com/",
    serviceImg: "/Featured-8.png",
    review: "4.1 | 50+ reviews",
    h1: "UOB",
    titleone: "Fresher",
    titletwo: "Jakarta",
    time: "23 houre ago",
    listone: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listtwo: "Internship",
    listthree: "Hybrid",
    listfour: "Tech Rookie Internship Program (TRIP) - Data Analyst Intern",
    listfive: "Internship",
    listsix: "Hybrid",
    skilone: "SQL",
    skiltwo: "Tableau",
    skilthree: "Python",
    skilfour: "Attention To Detail",
    skilfive: "Critical Thinking",
  },
];

export default FeaturedData;
